# Generated by Django 5.1.1 on 2024-09-30 09:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('Department_name'), name='unique_department_name_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_name', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('Designation_name'), name='unique_designation_name_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Employee_name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=100)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('Branch', models.CharField(blank=True, max_length=100, null=True)),
                ('Personal_Admin', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_of_Joining', models.DateField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Degree', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_Id', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('Mobile_Number', models.IntegerField(blank=True, null=True, unique=True)),
                ('Current_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Permanent_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Aadhaar_Number', models.IntegerField(blank=True, null=True, unique=True)),
                ('Punching_Machine_Code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('PAN_No', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('EPF_No', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ESI_No', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Target', models.IntegerField(blank=True, null=True)),
                ('Employee_Image', models.ImageField(blank=True, null=True, upload_to='Employee_Images/')),
                ('Employee_Signature', models.ImageField(blank=True, null=True, upload_to='Employee_Signature/')),
                ('User_Menu_Permission', models.CharField(blank=True, max_length=200, null=True)),
                ('Login_Name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Previous_Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Experience_In_Years', models.IntegerField(blank=True, null=True)),
                ('Reference_Through', models.CharField(blank=True, max_length=100, null=True)),
                ('Previous_Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Reference_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Number', models.IntegerField(blank=True, null=True, unique=True)),
                ('Account_Holder_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Salary_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Permission_Amount_Per_Hour', models.IntegerField(blank=True, null=True)),
                ('Professional_Tax', models.IntegerField(blank=True, null=True)),
                ('Working_Hours', models.IntegerField(blank=True, null=True)),
                ('Basic_Pay', models.FloatField(blank=True, null=True)),
                ('RD', models.FloatField(blank=True, null=True)),
                ('Casual_Leave_Per_Month', models.IntegerField(blank=True, null=True)),
                ('HRA', models.FloatField(blank=True, null=True)),
                ('PF', models.FloatField(blank=True, null=True)),
                ('Sick_Leave_Per_Month', models.IntegerField(blank=True, null=True)),
                ('Medical_Allowance', models.FloatField(blank=True, null=True)),
                ('ESI', models.IntegerField(blank=True, null=True)),
                ('Over_Time_Amount_Per_Hour', models.FloatField(blank=True, null=True)),
                ('Conveyance_Allowance', models.FloatField(blank=True, null=True)),
                ('Loss_of_Pay_Per_Day', models.FloatField(blank=True, null=True)),
                ('General_Allowance', models.FloatField(blank=True, null=True)),
                ('Net_Salary', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Business.department')),
                ('Designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Business.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance_status', models.CharField(max_length=100)),
                ('Attendance_Date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='Business.employee')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=100, unique=True)),
                ('State_code', models.CharField(max_length=100)),
                ('State_Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='State_Countries', to='Business.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=100, unique=True)),
                ('City_Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='City_countries', to='Business.country')),
                ('City_State', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='City_states', to='Business.state')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(max_length=100, unique=True)),
                ('Area_City', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area_cities', to='Business.city')),
                ('Area_Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area_countries', to='Business.country')),
                ('Area_State', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area_states', to='Business.state')),
            ],
        ),
    ]
