# Generated by Django 5.1.1 on 2024-09-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance_status', models.CharField(max_length=100)),
                ('Attendance_Date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='Business.employee')),
            ],
        ),
    ]
