# Generated by Django 5.1.1 on 2024-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_attendancemenus1_delete_attendancemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holiday_select', models.CharField(blank=True, max_length=100, null=True)),
                ('Week_off_select', models.CharField(blank=True, max_length=100, null=True)),
                ('Holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Holiday_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
