# Generated by Django 5.1.1 on 2024-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='Holiday_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
